# Site settings
author: Ben
title: Learning to Computer
header-img: img/home-bg.png
email: ben20262@aim.com
copyright_name: Ben
description: > # this means to ignore newlines until "baseurl:"
  Learning to Compute in a Computer Driven World
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ben20262

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
